#!/usr/bin/env bash
echo "== delete bucket"

set -e

# Check if at least one argument is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-buckets --bucket $BUCKET_NAME

